de_data = [
    # --- OLMOSHLAR ---
    ["men", "ich", "-", "-"],
    ["sen", "du", "-", "-"],
    ["u (o'g'il)", "er", "-", "-"],
    ["u (qiz)", "sie", "-", "-"],
    ["biz", "wir", "-", "-"],
    ["siz", "ihr/Sie", "-", "-"],
    ["ular", "sie", "-", "-"],
    ["meniki", "mein", "-", "-"],
    ["seniki", "dein", "-", "-"],
    ["uniki (o'g'il)", "sein", "-", "-"],
    ["uniki (qiz)", "ihr", "-", "-"],
    ["menda bor", "ich habe", "-", "-"],
    ["senda bor", "du hast", "-", "-"],

    # --- MEVALAR VA SABZAVOTLAR ---
    ["olma", "Apfel", "der", "Äpfel"],
    ["banan", "Banane", "die", "Bananen"],
    ["limon", "Zitrone", "die", "Zitronen"],
    ["uzum", "Traube", "die", "Trauben"],
    ["qovun", "Melone", "die", "Melonen"],
    ["shaftoli", "Pfirsich", "der", "Pfirsiche"],
    ["kartoshka", "Kartoffel", "die", "Kartoffeln"],
    ["piyoz", "Zwiebel", "die", "Zwiebeln"],
    ["pomidor", "Tomate", "die", "Tomaten"],
    ["bodring", "Gurke", "die", "Gurken"],
    ["sabzi", "Karotte", "die", "Karotten"],
    ["sarimsoq", "Knoblauch", "der", "-"],

    # --- OILA VA QARINDOSHLAR (Asosiy) ---
    ["ota", "Vater", "der", "Väter"],
    ["ona", "Mutter", "die", "Mütter"],
    ["o'g'il", "Sohn", "der", "Söhne"],
    ["qiz", "Tochter", "die", "Töchter"],
    ["aka/uka", "Bruder", "der", "Brüder"],
    ["opa/singil", "Schwester", "die", "Schwestern"],
    ["buva", "Großvater", "der", "Großväter"],
    ["buvi", "Großmutter", "die", "Großmütter"],
    ["er", "Ehemann", "der", "Ehemänner"],
    ["xotin", "Ehefrau", "die", "Ehefrauen"],
    ["ota-ona", "Eltern", "die", "-"],
    ["farzandlar", "Kinder", "die", "-"],
    ["egizaklar", "Zwillinge", "die", "-"],
    ["er-xotin", "Ehepaar", "das", "Ehepaare"],

    # --- KENGAYTIRILGAN QARINDOSHLIK ---
    ["qaynona", "Schwiegermutter", "die", "Schwiegermütter"],
    ["qaynota", "Schwiegervater", "der", "Schwiegerväter"],
    ["kelin", "Schwiegertochter", "die", "Schwiegertöchter"],
    ["kuyov", "Schwiegersohn", "der", "Schwiegersöhne"],
    ["qayinaga / qayini", "Schwager", "der", "Schwäger"],
    ["qayinsingil / qayniopa", "Schwägerin", "die", "Schwägerinnen"],
    ["o'gay ota", "Stiefvater", "der", "Stiefväter"],
    ["o'gay ona", "Stiefmutter", "die", "Stiefmütter"],
    ["ajdodlar", "Vorfahren", "die", "-"],
    ["avlodlar", "Nachkommen", "die", "-"],
    ["qarindosh (ayol)", "Verwandte", "die", "Verwandten"],
    ["qarindosh (erkak)", "Verwandter", "der", "Verwandten"],
    ["katta bobo", "Urgroßvater", "der", "Urgroßväter"],
    ["katta buvi", "Urgroßmutter", "die", "Urgroßmütter"],
    ["amaki / tog‘a", "Onkel", "der", "Onkel"],
    ["amma / xola", "Tante", "die", "Tanten"],
    ["amakivachcha / tog‘avachcha (erkak)", "Cousin", "der", "Cousins"],
    ["ammavachcha / xolavachcha (ayol)", "Cousine", "die", "Cousinen"],
    ["kelinoyi / yanga", "Schwägerin", "die", "Schwägerinnen"],
    ["pochcha", "Schwager", "der", "Schwäger"],
    ["oila a'zosi", "Familienmitglied", "das", "Familienmitglieder"],
    ["qarindoshlik", "Verwandtschaft", "die", "-"],
    ["yetim", "Waise", "die", "Waisen"],
    ["asrab olingan bola", "Adoptivkind", "das", "Adoptivkinder"],

    # --- TANA A'ZOLARI ---
    ["bosh", "Kopf", "der", "Köpfe"],
    ["ko'z", "Auge", "das", "Augen"],
    ["quloq", "Ohr", "das", "Ohren"],
    ["burun", "Nase", "die", "Nasen"],
    ["og'iz", "Mund", "der", "Münder"],
    ["qo'l", "Hand", "die", "Hände"],
    ["oyoq", "Fuß", "der", "Füße"],
    ["yurak", "Herz", "das", "Herzen"],
    ["soch", "Haar", "das", "Haare"],
    ["tish", "Zahn", "der", "Zähne"],

    # --- KUNDALIK FE'LLAR ---
    ["yemoq", "essen", "-", "-"],
    ["ichmoq", "trinken", "-", "-"],
    ["uxlamoq", "schlafen", "-", "-"],
    ["uyg'onmoq", "aufwachen", "-", "-"],
    ["bormoq", "gehen", "-", "-"],
    ["kelmoq", "kommen", "-", "-"],
    ["ishlamoq", "arbeiten", "-", "-"],
    ["o'qimoq", "lesen", "-", "-"],
    ["yozmoq", "schreiben", "-", "-"],
    ["gapirmoq", "sprechen", "-", "-"],
    ["ko'rmoq", "sehen", "-", "-"],
    ["eshitmoq", "hören", "-", "-"],
    ["sotib olmoq", "kaufen", "-", "-"],
    ["to'lamoq", "bezahlen", "-", "-"],

    # --- VAQT VA KUNLAR ---
    ["bugun", "heute", "-", "-"],
    ["ertaga", "morgen", "-", "-"],
    ["kecha", "gestern", "-", "-"],
    ["hozir", "jetzt", "-", "-"],
    ["dushanba", "Montag", "der", "-"],
    ["seshanba", "Dienstag", "der", "-"],
    ["chorshanba", "Mittwoch", "der", "-"],
    ["payshanba", "Donnerstag", "der", "-"],
    ["juma", "Freitag", "der", "-"],
    ["shanba", "Samstag", "der", "-"],
    ["yakshanba", "Sonntag", "der", "-"],

    # --- SIFATLAR ---
    ["yaxshi", "gut", "-", "-"],
    ["yomon", "schlecht", "-", "-"],
    ["issiq", "heiß", "-", "-"],
    ["sovuq", "kalt", "-", "-"],
    ["katta", "groß", "-", "-"],
    ["kichik", "klein", "-", "-"],
    ["chiroyli", "schön", "-", "-"],
    ["tez", "schnell", "-", "-"],
    ["sekin", "langsam", "-", "-"],
    ["yangi", "neu", "-", "-"],
    ["eski", "alt", "-", "-"],
    ["og'ir", "schwer", "-", "-"],
    ["yengil", "leicht", "-", "-"]
]
